### ISSUE TITLE
Generating Input data for vFI

### ISSUE THREAD

**Issue by S-Watanabe0123** [KumarLabJax/vFI-modeling#2]
Hello,

I would like to use vFI model to assess the frailty index of mice, but I am confused about the generating input data (like df_video_features.csv). As far as I understand, the scripts I need to run to get all the features are depicted in the diagram below. Could you confirm if this is correct? If there is something missing, please let me know. 

![vFI pipeline](https://user-images.githubusercontent.com/90536715/197570705-eda5d70b-6dab-448c-94ee-788906d91aeb.png)

**Comment by SkepticRaven** [comment]
This repository only handles the last block in that diagram.
The scripts to generate features used here originate as output from this other repo: https://github.com/KumarLabJax/vFI-features
That repository only handles most of the 3rd column blocks in this diagram (width, flexibility, rearing). It also points to the relevant repositories for generating the 2nd column + remainder of blocks in 3rd column.

@gautam-sabnis - You should probably point to this repo in the docs to avoid future confusion.

**Comment by S-Watanabe0123** [comment]
Thank you, @SkepticRaven. 
I will try to run each repository and ask questions when needed.
